id: P010592
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:35.333468
source_metadata:
  id: bdr:W20404
  title: ཚད་མའི་བསྟན་བཅོས་རིགས་པའི་རྒྱན།
  author: ''
  volumes:
    9de8506e1f03427091028e98da0bd561:
      image_group_id: I1KG10359
      title: ''
      volume_number: 1
      total_pages: 512
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
