id: IED9333E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:16:23+00:00'
last_modified: '2022-06-08T16:05:59.208555+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20404
  title: ཚད་མའི་བསྟན་བཅོས་རིགས་པའི་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D82B:
      image_group_id: I1KG10359
      title: ''
      total_pages: 512
      order: 1
      base_file: D82B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
